theme = "showfolio"
languageCode = "en-us"
baseurl = "https://nppi3enz.github.io"
title = "NPPiProfile"


[params]
  name = "Showfolio Theme"
  description = "Modern portfolio theme for your Hugo site."
  author = "Nipitpon Chantada"
  authorEmail = "name@example.com"
  authorImage = "/img/pic.jpg"
  autoDarkMode = true

  copyright = "Copyright © 2021 - John Doe · All rights reserved"
  favicon = "favicon.ico"

[params.homepage]
  title = "Nipitpon Chantada"
  tagline = "Full Stack Developer"
  description = "I’m working in Bangkok for finding technology-related big project management experiences and being a skillful developer."
  contact = "https://www.linkedin.com/in/nppi3enz/"

[params.homepage.codepen]
  username = "apvarun"
  pens = ["MQaRKL", "RxodrP", "BmXGdm", "wdVypQ"]

[params.homepage.resume]
  skills = ["Product Development"]

[[params.homepage.resume.work]]
  name = "EGG Digital Co, Ltd."
  role = "PHP Developer"
  duration = "November 2018 - Present"
  description = "I am backend developer. Develop point-of-sale System for work in restaurant, retail. Create until web portal to backend system for use in mobile application."

[[params.homepage.resume.work]]
  name = "Dfusion Co, Ltd."
  role = "Developer"
  duration = "August 2017 - October 2018"
  description = "I am frontend and backend developer. Not only creating website or minisite to surve marketing campaign, such as photo booth or ticketing system, but also be part of business development such as B2B affiliate system and lead evaluator system. I have worked with big name company like TOYOTA, BMW, Lin sugar, Swatch."

[[params.homepage.resume.work]]
  name = "SHIPPOP Co, Ltd."
  role = "Web Developer"
  duration = "July 2016 - July 2017"
  description = "I have developed both frontend and backend systems. To make the user more comfortable connecting with new carriers."

[[params.homepage.resume.work]]
  name = "DEK-D Co, Ltd."
  role = "Web Developer (Intern)"
  duration = "April 2014 - May 2014"
  description = "I am responsible for research and develop UI/UX of visual novel system."

[params.homepage.social]
  twitter = ""
  linkedin = "https://linkedin.com/in/nppi3enz"
  github = "https://github.com/nppi3enz"
  medium = "https://medium.com/@nppi3enz"
  reddit = ""
  dribbble = ""

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
