baseURL = "/"
languageCode = "en-us"
title = "NPPi3enz's Profile"
theme = "hugo-resume"

[params]
    firstName = "Nipitpon"
    lastName = "Chantada"
    address = "Bangkok, Thailand"
    phone = "1-555-555-1234"
    contactNote = "Dev Tools Engineer"
    profileImage = "img/avatar.jpg"
    email = "nppi3enz@gmail.com"
    description = "Sss"
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true

    showQr = false

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/nppi3enz/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/nppi3enz/"

[[params.handles]]
    name = "Bitbucket"
    link = "https://bitbucket.org/nppi3enz/"

#[[params.handles]]
#    name = "Stack Overflow"
#    link = "https://stackoverflow.com/users/story/82880"
#    icon = "stack-overflow"

#[[params.handles]]
#    name = "Keybase"
#    link = "https://keybase.io/edwardawebb"
#    icon = "keybase"

[params.google.analytics]
    trackerID = "XX-123446-01"
